# Generated by Django 4.1.1 on 2023-03-11 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left', models.IntegerField()),
                ('right', models.IntegerField()),
                ('straight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id_celery', models.CharField(max_length=255, unique=True)),
                ('date_done', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_total', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id_celery', models.CharField(max_length=50)),
                ('date_time', models.CharField(max_length=50)),
                ('date_time_modify', models.DateTimeField(auto_now=True)),
                ('date_time_upload', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('status', models.CharField(default='UNPROCESS', max_length=50)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('time', models.CharField(max_length=50)),
                ('task_result', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.taskresult')),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('loop_name', models.CharField(max_length=50)),
                ('coordinates_x', models.IntegerField()),
                ('coordinates_y', models.IntegerField()),
                ('head_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
