# Generated by Django 4.2 on 2023-04-25 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoopResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_id', models.IntegerField()),
                ('summary_file', models.FileField(null=True, upload_to='result/summary/')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id_celery', models.CharField(max_length=50, null=True)),
                ('date_time', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('date_time_modify', models.DateTimeField(auto_now=True)),
                ('date_time_upload', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('longtitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('video_file', models.FileField(upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])])),
                ('video_result_file', models.FileField(null=True, upload_to='result/video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov'])])),
                ('counting_result_file', models.FileField(null=True, upload_to='result/counting/')),
                ('image_file', models.ImageField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_id', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('entered', models.IntegerField()),
                ('straight', models.IntegerField()),
                ('right', models.IntegerField()),
                ('left', models.IntegerField()),
                ('loop_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.loopresult')),
            ],
        ),
        migrations.AddField(
            model_name='loopresult',
            name='task_loop_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop_name', models.CharField(max_length=255)),
                ('loop_id', models.IntegerField()),
                ('orientation', models.CharField(max_length=255)),
                ('x_1', models.IntegerField()),
                ('y_1', models.IntegerField()),
                ('x_2', models.IntegerField()),
                ('y_2', models.IntegerField()),
                ('x_3', models.IntegerField()),
                ('y_3', models.IntegerField()),
                ('x_4', models.IntegerField()),
                ('y_4', models.IntegerField()),
                ('summary_location_x', models.IntegerField()),
                ('summary_location_y', models.IntegerField()),
                ('head_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
