# Generated by Django 4.1.1 on 2023-04-15 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_file',
            field=models.ImageField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
